# Generated by Django 4.0.3 on 2022-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoinfo',
            name='list_size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
