# Generated by Django 4.0.3 on 2022-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_geoinfo_list_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoinfo',
            name='iata_airport_code',
            field=models.CharField(max_length=200),
        ),
    ]
