# Generated by Django 4.0.3 on 2022-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_geoposition_remove_geoinfo_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoinfo',
            name='geo_position',
        ),
        migrations.AddField(
            model_name='geoinfo',
            name='latitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoinfo',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GeoPosition',
        ),
    ]
