# Generated by Django 4.0.3 on 2022-04-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_geoinfo_geo_position_geoinfo_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='longitude',
        ),
        migrations.AddField(
            model_name='geoinfo',
            name='geo_position',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.geoposition'),
            preserve_default=False,
        ),
    ]
